### PR TITLE
Support UE5 early access

### PR DESCRIPTION
**Pull request by realvictorprm**
These are the changes with which I successfully managed to get the plugin to compile again.

### CODE REVIEW

**Review by nxrighthere — CHANGES_REQUESTED** [review]
Could you please add indentation before each `#define` (tabs).

**Comment by realvictorprm** [comment]
will do

**Comment by nxrighthere** [comment]
Closed in favor of https://github.com/nxrighthere/UnrealCLR/commit/1042c5f613a82a053c714afe8b43ea81c812ad8e.

**Comment by realvictorprm** [comment]
Well couldn't do the stuff earlier as I was busy including sleeping 😄

**Comment by realvictorprm** [comment]
next time leave me a bit more time please

**Pull request closed without merging**
