### PR TITLE
Expose `AddInstances` for `InstancedStaticMeshComponent`

### PR DESCRIPTION
**Pull request by realvictorprm**
Not exactly sure whether this is correct but I try my best.

### CODE REVIEW

**Comment by nxrighthere** [comment]
This code is invalid. Manipulations with arrays between native and managed sides should be handled through intermediate conversion (see implementation of [`InstancedStaticMeshComponent.BatchUpdateInstanceTransforms()`](https://github.com/nxrighthere/UnrealCLR/blob/8f211871beb2146ae0975b1a6981cc0e8ee6ddec/Source/Native/Source/UnrealCLR/Private/UnrealCLRFramework.cpp#L3428)).

Also, the managed function in the framework shouldn't return an unmanaged pointer. User-code supposed to be memory-safe and operate only with managed memory.

**Comment by realvictorprm** [comment]
Yeah noticed too that the code is not working yet. Should convert this to a draft as this is still wip.

Can you tell me how I can set up everything such that I have a VS project which I can open in Visual Studio? Would like to sort out that part as quick as possible to fix the code.

Thanks for the link, happy to have some direction here on quality etc.

**Comment by nxrighthere** [comment]
> Can you tell me how I can set up everything such that I have a VS project which I can open in Visual Studio? Would like to sort out that part as quick as possible to fix the code.

Please, follow [these](https://docs.unrealengine.com/en-US/ProductionPipelines/DevelopmentSetup/VisualStudioSetup/index.html) instructions. Make sure that `uproject` files are associated with the engine, so all you have to do after setting up Visual Studio is right-click on your project file and generate a solution.

**Comment by realvictorprm** [comment]
I tried to follow that guide already, however I wasn't able to generate a project file for the `uplugin` file :/

**Comment by nxrighthere** [comment]
It should be possible to generate it from the context menu.

Context menu

As an alternative, you can add a new empty C++ class to the project in the editor and the solution should be generated automatically.

**Comment by nxrighthere** [comment]
Closed in favor of https://github.com/nxrighthere/UnrealCLR/commit/26cba91d348f530d4f92259748ee0bdf4bd6b54c.

**Comment by realvictorprm** [comment]
Many thanks :)

**Pull request closed without merging**
